/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as CertificationsCredentialIdRouteImport } from './routes/certifications.$credentialId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiCertificatesAssetIdRouteImport } from './routes/api/certificates/$assetId'
import { Route as ApiAdminAuditExportRouteImport } from './routes/api/admin/audit/export'
import { Route as ApiAdminCertificatesValidateRouteImport } from './routes/api/admin/certificates/validate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const CertificationsCredentialIdRoute =
  CertificationsCredentialIdRouteImport.update({
    id: '/certifications/$credentialId',
    path: '/certifications/$credentialId',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCertificatesAssetIdRoute = ApiCertificatesAssetIdRouteImport.update({
  id: '/api/certificates/$assetId',
  path: '/api/certificates/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuditExportRoute = ApiAdminAuditExportRouteImport.update({
  id: '/api/admin/audit/export',
  path: '/api/admin/audit/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCertificatesValidateRoute =
  ApiAdminCertificatesValidateRouteImport.update({
    id: '/api/admin/certificates/validate',
    path: '/api/admin/certificates/validate',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/resume': typeof ResumeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/certifications/$credentialId': typeof CertificationsCredentialIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/certificates/$assetId': typeof ApiCertificatesAssetIdRoute
  '/api/admin/audit/export': typeof ApiAdminAuditExportRoute
  '/api/admin/certificates/validate': typeof ApiAdminCertificatesValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/resume': typeof ResumeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/certifications/$credentialId': typeof CertificationsCredentialIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/certificates/$assetId': typeof ApiCertificatesAssetIdRoute
  '/api/admin/audit/export': typeof ApiAdminAuditExportRoute
  '/api/admin/certificates/validate': typeof ApiAdminCertificatesValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/resume': typeof ResumeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/certifications/$credentialId': typeof CertificationsCredentialIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/certificates/$assetId': typeof ApiCertificatesAssetIdRoute
  '/api/admin/audit/export': typeof ApiAdminAuditExportRoute
  '/api/admin/certificates/validate': typeof ApiAdminCertificatesValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/resume'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/certifications/$credentialId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/certificates/$assetId'
    | '/api/admin/audit/export'
    | '/api/admin/certificates/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/resume'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/certifications/$credentialId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/certificates/$assetId'
    | '/api/admin/audit/export'
    | '/api/admin/certificates/validate'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/mcp'
    | '/resume'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/certifications/$credentialId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/certificates/$assetId'
    | '/api/admin/audit/export'
    | '/api/admin/certificates/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResumeRoute: typeof ResumeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CertificationsCredentialIdRoute: typeof CertificationsCredentialIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiCertificatesAssetIdRoute: typeof ApiCertificatesAssetIdRoute
  ApiAdminAuditExportRoute: typeof ApiAdminAuditExportRoute
  ApiAdminCertificatesValidateRoute: typeof ApiAdminCertificatesValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications/$credentialId': {
      id: '/certifications/$credentialId'
      path: '/certifications/$credentialId'
      fullPath: '/certifications/$credentialId'
      preLoaderRoute: typeof CertificationsCredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certificates/$assetId': {
      id: '/api/certificates/$assetId'
      path: '/api/certificates/$assetId'
      fullPath: '/api/certificates/$assetId'
      preLoaderRoute: typeof ApiCertificatesAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/audit/export': {
      id: '/api/admin/audit/export'
      path: '/api/admin/audit/export'
      fullPath: '/api/admin/audit/export'
      preLoaderRoute: typeof ApiAdminAuditExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/certificates/validate': {
      id: '/api/admin/certificates/validate'
      path: '/api/admin/certificates/validate'
      fullPath: '/api/admin/certificates/validate'
      preLoaderRoute: typeof ApiAdminCertificatesValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResumeRoute: ResumeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CertificationsCredentialIdRoute: CertificationsCredentialIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiCertificatesAssetIdRoute: ApiCertificatesAssetIdRoute,
  ApiAdminAuditExportRoute: ApiAdminAuditExportRoute,
  ApiAdminCertificatesValidateRoute: ApiAdminCertificatesValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
